const puppeteer = require('puppeteer');
const fs = require('fs');
const path = require('path');
const cidadesSP = [
    { nome: "Adamantina", codigo: 1, regiao: 10},
    { nome: "Adolfo", codigo: 2, regiao: 7},
    { nome: "Aguaí", codigo: 3, regiao: 11},
    { nome: "Águas da Prata", codigo: 4, regiao: 11},
    { nome: "Águas de Lindóia", codigo: 5, regiao: 4},
    { nome: "Águas de Santa Bárbara", codigo: 6, regiao: 9},
    { nome: "Águas de São Pedro", codigo: 7, regiao: 11},
    { nome: "Agudos", codigo: 8, regiao: 6},
    { nome: "Alambari", codigo: 9, regiao: 9},
    { nome: "Alfredo Marcondes", codigo: 10, regiao: 10},
    { nome: "Altair", codigo: 11, regiao: 5},
    { nome: "Altinópolis", codigo: 12, regiao: 5},
    { nome: "Alto Alegre", codigo: 13, regiao: 12},
    { nome: "Alumínio", codigo: 14, regiao: 9},
    { nome: "Álvares Florence", codigo: 15, regiao: 7},
    { nome: "Álvares Machado", codigo: 16, regiao: 10},
    { nome: "Álvaro de Carvalho", codigo: 17, regiao: 6},
    { nome: "Alvinlândia", codigo: 18, regiao: 6},
    { nome: "Americana", codigo: 19, regiao: 11},
    { nome: "Américo Brasiliense", codigo: 20, regiao: 5},
    { nome: "Américo de Campos", codigo: 21, regiao: 7},
    { nome: "Amparo", codigo: 22, regiao: 4},
    { nome: "Analândia", codigo: 23, regiao: 11},
    { nome: "Andradina", codigo: 24, regiao: 12},
    { nome: "Angatuba", codigo: 25, regiao: 9},
    { nome: "Anhembi", codigo: 26, regiao: 9},
    { nome: "Anhumas", codigo: 27, regiao: 10},
    { nome: "Aparecida", codigo: 28, regiao: 3},
    { nome: "Aparecida D´Oeste", codigo: 29, regiao: 7},
    { nome: "Apiaí", codigo: 30, regiao: 9},
    { nome: "Araçariguama", codigo: 31, regiao: 9},
    { nome: "Araçatuba", codigo: 32, regiao: 12},
    { nome: "Araçoiaba da Serra", codigo: 33, regiao: 9},
    { nome: "Aramina", codigo: 34, regiao: 5},
    { nome: "Arandu", codigo: 35, regiao: 9},
    { nome: "Arapeí", codigo: 36, regiao: 3},
    { nome: "Araraquara", codigo: 37, regiao: 5},
    { nome: "Araras", codigo: 38, regiao: 11},
    { nome: "Arco-Íris", codigo: 39, regiao: 6},
    { nome: "Arealva", codigo: 40, regiao: 6},
    { nome: "Areias", codigo: 41, regiao: 3},
    { nome: "Areiópolis", codigo: 42, regiao: 9},
    { nome: "Ariranha", codigo: 43, regiao: 7},
    { nome: "Artur Nogueira", codigo: 44, regiao: 11},
    { nome: "Arujá", codigo: 45, regiao: 2},
    { nome: "Aspásia", codigo: 46, regiao: 7},
    { nome: "Assis", codigo: 47, regiao: 10},
    { nome: "Atibaia", codigo: 48, regiao: 4},
    { nome: "Auriflama", codigo: 49, regiao: 12},
    { nome: "Avaí", codigo: 50, regiao: 6},
    { nome: "Avanhandava", codigo: 51, regiao: 12},
    { nome: "Avaré", codigo: 52, regiao: 9},
    { nome: "Bady Bassitt", codigo: 53, regiao: 7},
    { nome: "Balbinos", codigo: 54, regiao: 6},
    { nome: "Bálsamo", codigo: 55, regiao: 7},
    { nome: "Bananal", codigo: 56, regiao: 3},
    { nome: "Barão de Antonina", codigo: 57, regiao: 9},
    { nome: "Barbosa", codigo: 58, regiao: 12},
    { nome: "Bariri", codigo: 59, regiao: 6},
    { nome: "Barra Bonita", codigo: 60, regiao: 6},
    { nome: "Barra do Chapéu", codigo: 61, regiao: 9},
    { nome: "Barra do Turvo", codigo: 62, regiao: 8},
    { nome: "Barretos", codigo: 63, regiao: 5},
    { nome: "Barrinha", codigo: 64, regiao: 5},
    { nome: "Barueri", codigo: 65, regiao: 2},
    { nome: "Bastos", codigo: 66, regiao: 6},
    { nome: "Batatais", codigo: 67, regiao: 5},
    { nome: "Bauru", codigo: 68, regiao: 6},
    { nome: "Bebedouro", codigo: 69, regiao: 5},
    { nome: "Bento de Abreu", codigo: 70, regiao: 12},
    { nome: "Bernardino de Campos", codigo: 71, regiao: 6},
    { nome: "Bertioga", codigo: 72, regiao: 8},
    { nome: "Bilac", codigo: 73, regiao: 12},
    { nome: "Birigui", codigo: 74, regiao: 12},
    { nome: "Biritiba Mirim", codigo: 75, regiao: 2},
    { nome: "Boa Esperança do Sul", codigo: 76, regiao: 5},
    { nome: "Bocaina", codigo: 77, regiao: 6},
    { nome: "Bofete", codigo: 78, regiao: 9},
    { nome: "Boituva", codigo: 79, regiao: 9},
    { nome: "Bom Jesus dos Perdões", codigo: 80, regiao: 4},
    { nome: "Bom Sucesso de Itararé", codigo: 81, regiao: 9},
    { nome: "Borá", codigo: 82, regiao: 6},
    { nome: "Boraceia", codigo: 83, regiao: 6},
    { nome: "Borborema", codigo: 84, regiao: 5},
    { nome: "Borebi", codigo: 85, regiao: 6},
    { nome: "Botucatu", codigo: 86, regiao: 9},
    { nome: "Bragança Paulista", codigo: 87, regiao: 4},
    { nome: "Braúna", codigo: 88, regiao: 12},
    { nome: "Brejo Alegre", codigo: 89, regiao: 12},
    { nome: "Brodowski", codigo: 90, regiao: 5},
    { nome: "Brotas", codigo: 91, regiao: 11},
    { nome: "Buri", codigo: 92, regiao: 9},
    { nome: "Buritama", codigo: 93, regiao: 12},
    { nome: "Buritizal", codigo: 94, regiao: 5},
    { nome: "Cabrália Paulista", codigo: 95, regiao: 6},
    { nome: "Cabreúva", codigo: 96, regiao: 4},
    { nome: "Caçapava", codigo: 97, regiao: 3},
    { nome: "Cachoeira Paulista", codigo: 98, regiao: 3},
    { nome: "Caconde", codigo: 99, regiao: 11},
    { nome: "Cafelândia", codigo: 100, regiao: 6},
    { nome: "Caiabu", codigo: 101, regiao: 10},
    { nome: "Caieiras", codigo: 102, regiao: 2},
    { nome: "Caiuá", codigo: 103, regiao: 10},
    { nome: "Cajamar", codigo: 104, regiao: 2},
    { nome: "Cajati", codigo: 105, regiao: 8},
    { nome: "Cajobi", codigo: 106, regiao: 5},
    { nome: "Cajuru", codigo: 107, regiao: 5},
    { nome: "Campina do Monte Alegre", codigo: 108, regiao: 9},
    { nome: "Campinas", codigo: 109, regiao: 4},
    { nome: "Campo Limpo Paulista", codigo: 110, regiao: 4},
    { nome: "Campos do Jordão", codigo: 111, regiao: 3},
    { nome: "Campos Novos Paulista", codigo: 112, regiao: 10},
    { nome: "Cananeia", codigo: 113, regiao: 8},
    { nome: "Canas", codigo: 114, regiao: 3},
    { nome: "Cândido Mota", codigo: 115, regiao: 10},
    { nome: "Cândido Rodrigues", codigo: 116, regiao: 5},
    { nome: "Canitar", codigo: 117, regiao: 6},
    { nome: "Capão Bonito", codigo: 118, regiao: 9},
    { nome: "Capela do Alto", codigo: 119, regiao: 9},
    { nome: "Capivari", codigo: 120, regiao: 11},
    { nome: "Caraguatatuba", codigo: 121, regiao: 3},
    { nome: "Carapicuíba", codigo: 122, regiao: 2},
    { nome: "Cardoso", codigo: 123, regiao: 7},
    { nome: "Casa Branca", codigo: 124, regiao: 11},
    { nome: "Cássia dos Coqueiros", codigo: 125, regiao: 5},
    { nome: "Castilho", codigo: 126, regiao: 12},
    { nome: "Catanduva", codigo: 127, regiao: 7},
    { nome: "Catiguá", codigo: 128, regiao: 7},
    { nome: "Cedral", codigo: 129, regiao: 7},
    { nome: "Cerqueira César", codigo: 130, regiao: 9},
    { nome: "Cerquilho", codigo: 131, regiao: 9},
    { nome: "Cesário Lange", codigo: 132, regiao: 9},
    { nome: "Charqueada", codigo: 133, regiao: 11},
    { nome: "Chavantes", codigo: 134, regiao: 6},
    { nome: "Clementina", codigo: 135, regiao: 12},
    { nome: "Colina", codigo: 136, regiao: 5},
    { nome: "Colômbia", codigo: 137, regiao: 5},
    { nome: "Conchal", codigo: 138, regiao: 11},
    { nome: "Conchas", codigo: 139, regiao: 9},
    { nome: "Cordeirópolis", codigo: 140, regiao: 11},
    { nome: "Coroados", codigo: 141, regiao: 12},
    { nome: "Coronel Macedo", codigo: 142, regiao: 9},
    { nome: "Corumbataí", codigo: 143, regiao: 11},
    { nome: "Cosmópolis", codigo: 144, regiao: 11},
    { nome: "Cosmorama", codigo: 145, regiao: 7},
    { nome: "Cotia", codigo: 146, regiao: 2},
    { nome: "Cravinhos", codigo: 147, regiao: 5},
    { nome: "Cristais Paulista", codigo: 148, regiao: 5},
    { nome: "Cruzália", codigo: 149, regiao: 10},
    { nome: "Cruzeiro", codigo: 150, regiao: 3},
    { nome: "Cubatão", codigo: 151, regiao: 8},
    { nome: "Cunha", codigo: 152, regiao: 3},
    { nome: "Descalvado", codigo: 153, regiao: 5},
    { nome: "Diadema", codigo: 154, regiao: 2},
    { nome: "Dirce Reis", codigo: 155, regiao: 7},
    { nome: "Divinolândia", codigo: 156, regiao: 11},
    { nome: "Dobrada", codigo: 157, regiao: 5},
    { nome: "Dois Córregos", codigo: 158, regiao: 6},
    { nome: "Dolcinópolis", codigo: 159, regiao: 7},
    { nome: "Dourado", codigo: 160, regiao: 5},
    { nome: "Dracena", codigo: 161, regiao: 10},
    { nome: "Duartina", codigo: 162, regiao: 6},
    { nome: "Dumont", codigo: 163, regiao: 5},
    { nome: "Echaporã", codigo: 164, regiao: 6},
    { nome: "Eldorado", codigo: 165, regiao: 8},
    { nome: "Elias Fausto", codigo: 166, regiao: 11},
    { nome: "Elisiário", codigo: 167, regiao: 7},
    { nome: "Embaúba", codigo: 168, regiao: 5},
    { nome: "Embu das Artes", codigo: 169, regiao: 2},
    { nome: "Embu-Guaçu", codigo: 170, regiao: 2},
    { nome: "Emilianópolis", codigo: 171, regiao: 10},
    { nome: "Engenheiro Coelho", codigo: 172, regiao: 11},
    { nome: "Espírito Santo do Pinhal", codigo: 173, regiao: 11},
    { nome: "Espírito Santo do Turvo", codigo: 174, regiao: 6},
    { nome: "Estiva Gerbi", codigo: 175, regiao: 4},
    { nome: "Estrela D´Oeste", codigo: 176, regiao: 7},
    { nome: "Estrela do Norte", codigo: 177, regiao: 10},
    { nome: "Euclides da Cunha Paulista", codigo: 178, regiao: 10},
    { nome: "Fartura", codigo: 179, regiao: 9},
    { nome: "Fernando Prestes", codigo: 180, regiao: 5},
    { nome: "Fernandópolis", codigo: 181, regiao: 7},
    { nome: "Fernão", codigo: 182, regiao: 6},
    { nome: "Ferraz de Vasconcelos", codigo: 183, regiao: 2},
    { nome: "Flora Rica", codigo: 184, regiao: 10},
    { nome: "Floreal", codigo: 185, regiao: 7},
    { nome: "Flórida Paulista", codigo: 186, regiao: 10},
    { nome: "Florínia", codigo: 187, regiao: 10},
    { nome: "Franca", codigo: 188, regiao: 5},
    { nome: "Francisco Morato", codigo: 189, regiao: 2},
    { nome: "Franco da Rocha", codigo: 190, regiao: 2},
    { nome: "Gabriel Monteiro", codigo: 191, regiao: 12},
    { nome: "Gália", codigo: 192, regiao: 6},
    { nome: "Garça", codigo: 193, regiao: 6},
    { nome: "Gastão Vidigal", codigo: 194, regiao: 12},
    { nome: "Gavião Peixoto", codigo: 195, regiao: 5},
    { nome: "General Salgado", codigo: 196, regiao: 12},
    { nome: "Getulina", codigo: 197, regiao: 6},
    { nome: "Glicério", codigo: 198, regiao: 12},
    { nome: "Guaiçara", codigo: 199, regiao: 6},
    { nome: "Guaimbê", codigo: 200, regiao: 6},
    { nome: "Guaíra", codigo: 201, regiao: 5},
    { nome: "Guapiaçu", codigo: 202, regiao: 7},
    { nome: "Guapiara", codigo: 203, regiao: 9},
    { nome: "Guará", codigo: 204, regiao: 5},
    { nome: "Guaraçaí", codigo: 205, regiao: 12},
    { nome: "Guaraci", codigo: 206, regiao: 5},
    { nome: "Guarani D´Oeste", codigo: 207, regiao: 7},
    { nome: "Guarantã", codigo: 208, regiao: 6},
    { nome: "Guararapes", codigo: 209, regiao: 12},
    { nome: "Guararema", codigo: 210, regiao: 2},
    { nome: "Guaratinguetá", codigo: 211, regiao: 3},
    { nome: "Guareí", codigo: 212, regiao: 9},
    { nome: "Guariba", codigo: 213, regiao: 5},
    { nome: "Guarujá", codigo: 214, regiao: 8},
    { nome: "Guarulhos", codigo: 215, regiao: 2},
    { nome: "Guatapará", codigo: 216, regiao: 5},
    { nome: "Guzolândia", codigo: 217, regiao: 12},
    { nome: "Herculândia", codigo: 218, regiao: 6},
    { nome: "Holambra", codigo: 219, regiao: 4},
    { nome: "Hortolândia", codigo: 220, regiao: 11},
    { nome: "Iacanga", codigo: 221, regiao: 6},
    { nome: "Iacri", codigo: 222, regiao: 6},
    { nome: "Iaras", codigo: 223, regiao: 9},
    { nome: "Ibaté", codigo: 224, regiao: 5},
    { nome: "Ibirá", codigo: 225, regiao: 7},
    { nome: "Ibirarema", codigo: 226, regiao: 10},
    { nome: "Ibitinga", codigo: 227, regiao: 5},
    { nome: "Ibiúna", codigo: 228, regiao: 9},
    { nome: "Icém", codigo: 229, regiao: 7},
    { nome: "Iepê", codigo: 230, regiao: 10},
    { nome: "Igaraçu do Tietê", codigo: 231, regiao: 6},
    { nome: "Igarapava", codigo: 232, regiao: 5},
    { nome: "Igaratá", codigo: 233, regiao: 3},
    { nome: "Iguape", codigo: 234, regiao: 8},
    { nome: "Ilha Comprida", codigo: 235, regiao: 8},
    { nome: "Ilha Solteira", codigo: 236, regiao: 12},
    { nome: "Ilhabela", codigo: 237, regiao: 3},
    { nome: "Indaiatuba", codigo: 238, regiao: 4},
    { nome: "Indiana", codigo: 239, regiao: 10},
    { nome: "Indiaporã", codigo: 240, regiao: 7},
    { nome: "Inúbia Paulista", codigo: 241, regiao: 10},
    { nome: "Ipaussu", codigo: 242, regiao: 6},
    { nome: "Iperó", codigo: 243, regiao: 9},
    { nome: "Ipeúna", codigo: 244, regiao: 11},
    { nome: "Ipiguá", codigo: 245, regiao: 7},
    { nome: "Iporanga", codigo: 246, regiao: 8},
    { nome: "Ipuã", codigo: 247, regiao: 5},
    { nome: "Iracemápolis", codigo: 248, regiao: 11},
    { nome: "Irapuã", codigo: 249, regiao: 7},
    { nome: "Irapuru", codigo: 250, regiao: 10},
    { nome: "Itaberá", codigo: 251, regiao: 9},
    { nome: "Itaí", codigo: 252, regiao: 9},
    { nome: "Itajobi", codigo: 253, regiao: 7},
    { nome: "Itajú", codigo: 254, regiao: 6},
    { nome: "Itanhaém", codigo: 255, regiao: 8},
    { nome: "Itaoca", codigo: 256, regiao: 9},
    { nome: "Itapecerica da Serra", codigo: 257, regiao: 2},
    { nome: "Itapetininga", codigo: 258, regiao: 9},
    { nome: "Itapeva", codigo: 259, regiao: 9},
    { nome: "Itapevi", codigo: 260, regiao: 2},
    { nome: "Itapira", codigo: 261, regiao: 4},
    { nome: "Itapirapuã Paulista", codigo: 262, regiao: 9},
    { nome: "Itápolis", codigo: 263, regiao: 5},
    { nome: "Itaporanga", codigo: 264, regiao: 9},
    { nome: "Itapuí", codigo: 265, regiao: 6},
    { nome: "Itapura", codigo: 266, regiao: 12},
    { nome: "Itaquaquecetuba", codigo: 267, regiao: 2},
    { nome: "Itararé", codigo: 268, regiao: 9},
    { nome: "Itariri", codigo: 269, regiao: 8},
    { nome: "Itatiba", codigo: 270, regiao: 4},
    { nome: "Itatinga", codigo: 271, regiao: 9},
    { nome: "Itirapina", codigo: 272, regiao: 11},
    { nome: "Itirapuã", codigo: 273, regiao: 5},
    { nome: "Itobi", codigo: 274, regiao: 11},
    { nome: "Itu", codigo: 275, regiao: 9},
    { nome: "Itupeva", codigo: 276, regiao: 4},
    { nome: "Ituverava", codigo: 277, regiao: 5},
    { nome: "Jaborandi", codigo: 278, regiao: 5},
    { nome: "Jaboticabal", codigo: 279, regiao: 5},
    { nome: "Jacareí", codigo: 280, regiao: 3},
    { nome: "Jaci", codigo: 281, regiao: 7},
    { nome: "Jacupiranga", codigo: 282, regiao: 8},
    { nome: "Jaguariúna", codigo: 283, regiao: 4},
    { nome: "Jales", codigo: 284, regiao: 7},
    { nome: "Jambeiro", codigo: 285, regiao: 3},
    { nome: "Jandira", codigo: 286, regiao: 2},
    { nome: "Jardinópolis", codigo: 287, regiao: 5},
    { nome: "Jarinú", codigo: 288, regiao: 4},
    { nome: "Jaú", codigo: 289, regiao: 6},
    { nome: "Jeriquara", codigo: 290, regiao: 5},
    { nome: "Joanópolis", codigo: 291, regiao: 4},
    { nome: "João Ramalho", codigo: 292, regiao: 10},
    { nome: "José Bonifácio", codigo: 293, regiao: 7},
    { nome: "Júlio Mesquita", codigo: 294, regiao: 6},
    { nome: "Jumirim", codigo: 295, regiao: 9},
    { nome: "Jundiaí", codigo: 296, regiao: 4},
    { nome: "Junqueirópolis", codigo: 297, regiao: 10},
    { nome: "Juquiá", codigo: 298, regiao: 8},
    { nome: "Juquitiba", codigo: 299, regiao: 2},
    { nome: "Lagoinha", codigo: 300, regiao: 3},
    { nome: "Laranjal Paulista", codigo: 301, regiao: 9},
    { nome: "Lavínia", codigo: 302, regiao: 12},
    { nome: "Lavrinhas", codigo: 303, regiao: 3},
    { nome: "Leme", codigo: 304, regiao: 11},
    { nome: "Lençóis Paulista", codigo: 305, regiao: 6},
    { nome: "Limeira", codigo: 306, regiao: 11},
    { nome: "Lindoia", codigo: 307, regiao: 4},
    { nome: "Lins", codigo: 308, regiao: 6},
    { nome: "Lorena", codigo: 309, regiao: 3},
    { nome: "Lourdes", codigo: 310, regiao: 12},
    { nome: "Louveira", codigo: 311, regiao: 4},
    { nome: "Lucélia", codigo: 312, regiao: 10},
    { nome: "Lucianópolis", codigo: 313, regiao: 6},
    { nome: "Luís Antonio", codigo: 314, regiao: 5},
    { nome: "Luiziânia", codigo: 315, regiao: 12},
    { nome: "Lupércio", codigo: 316, regiao: 6},
    { nome: "Lutécia", codigo: 317, regiao: 10},
    { nome: "Macatuba", codigo: 318, regiao: 6},
    { nome: "Macaubal", codigo: 319, regiao: 7},
    { nome: "Macedônia", codigo: 320, regiao: 7},
    { nome: "Magda", codigo: 321, regiao: 7},
    { nome: "Mairinque", codigo: 322, regiao: 9},
    { nome: "Mairiporã", codigo: 323, regiao: 2},
    { nome: "Manduri", codigo: 324, regiao: 9},
    { nome: "Marabá Paulista", codigo: 325, regiao: 10},
    { nome: "Maracaí", codigo: 326, regiao: 10},
    { nome: "Marapoama", codigo: 327, regiao: 7},
    { nome: "Mariápolis", codigo: 328, regiao: 10},
    { nome: "Marília", codigo: 329, regiao: 6},
    { nome: "Marinópolis", codigo: 330, regiao: 7},
    { nome: "Martinópolis", codigo: 331, regiao: 10},
    { nome: "Matão", codigo: 332, regiao: 5},
    { nome: "Mauá", codigo: 333, regiao: 2},
    { nome: "Mendonça", codigo: 334, regiao: 7},
    { nome: "Meridiano", codigo: 335, regiao: 7},
    { nome: "Mesópolis", codigo: 336, regiao: 7},
    { nome: "Miguelópolis", codigo: 337, regiao: 5},
    { nome: "Mineiros do Tietê", codigo: 338, regiao: 6},
    { nome: "Mira Estrela", codigo: 339, regiao: 7},
    { nome: "Miracatu", codigo: 340, regiao: 8},
    { nome: "Mirandópolis", codigo: 341, regiao: 12},
    { nome: "Mirante do Paranapanema", codigo: 342, regiao: 10},
    { nome: "Mirassol", codigo: 343, regiao: 7},
    { nome: "Mirassolândia", codigo: 344, regiao: 7},
    { nome: "Mocóca", codigo: 345, regiao: 11},
    { nome: "Mogi das Cruzes", codigo: 346, regiao: 2},
    { nome: "Mogi-Guaçu", codigo: 347, regiao: 4},
    { nome: "Mogi-Mirim", codigo: 348, regiao: 4},
    { nome: "Mombuca", codigo: 349, regiao: 11},
    { nome: "Monções", codigo: 350, regiao: 7},
    { nome: "Mongaguá", codigo: 351, regiao: 8},
    { nome: "Monte Alegre do Sul", codigo: 352, regiao: 4},
    { nome: "Monte Alto", codigo: 353, regiao: 5},
    { nome: "Monte Aprazível", codigo: 354, regiao: 7},
    { nome: "Monte Azul Paulista", codigo: 355, regiao: 5},
    { nome: "Monte Castelo", codigo: 356, regiao: 10},
    { nome: "Monte Mor", codigo: 357, regiao: 11},
    { nome: "Monteiro Lobato", codigo: 358, regiao: 3},
    { nome: "Morro Agudo", codigo: 359, regiao: 5},
    { nome: "Morungaba", codigo: 360, regiao: 4},
    { nome: "Motuca", codigo: 361, regiao: 5},
    { nome: "Murutinga do Sul", codigo: 362, regiao: 12},
    { nome: "Nantes", codigo: 363, regiao: 10},
    { nome: "Narandiba", codigo: 364, regiao: 10},
    { nome: "Natividade da Serra", codigo: 365, regiao: 3},
    { nome: "Nazaré Paulista", codigo: 366, regiao: 4},
    { nome: "Neves Paulista", codigo: 367, regiao: 7},
    { nome: "Nhandeara", codigo: 368, regiao: 7},
    { nome: "Nipoã", codigo: 369, regiao: 7},
    { nome: "Nova Aliança", codigo: 370, regiao: 7},
    { nome: "Nova Campina", codigo: 371, regiao: 9},
    { nome: "Nova Canaã Paulista", codigo: 372, regiao: 7},
    { nome: "Nova Castilho", codigo: 373, regiao: 12},
    { nome: "Nova Europa", codigo: 374, regiao: 5},
    { nome: "Nova Granada", codigo: 375, regiao: 7},
    { nome: "Nova Guataporanga", codigo: 376, regiao: 10},
    { nome: "Nova Independência", codigo: 377, regiao: 12},
    { nome: "Nova Luzitânia", codigo: 378, regiao: 12},
    { nome: "Nova Odessa", codigo: 379, regiao: 11},
    { nome: "Novais", codigo: 380, regiao: 7},
    { nome: "Novo Horizonte", codigo: 381, regiao: 7},
    { nome: "Nuporanga", codigo: 382, regiao: 5},
    { nome: "Ocauçu", codigo: 383, regiao: 6},
    { nome: "Óleo", codigo: 384, regiao: 6},
    { nome: "Olímpia", codigo: 385, regiao: 5},
    { nome: "Onda Verde", codigo: 386, regiao: 7},
    { nome: "Oriente", codigo: 387, regiao: 6},
    { nome: "Orindiúva", codigo: 388, regiao: 7},
    { nome: "Orlândia", codigo: 389, regiao: 5},
    { nome: "Osasco", codigo: 390, regiao: 2},
    { nome: "Oscar Bressane", codigo: 391, regiao: 6},
    { nome: "Osvaldo Cruz", codigo: 392, regiao: 10},
    { nome: "Ourinhos", codigo: 393, regiao: 6},
    { nome: "Ouro Verde", codigo: 394, regiao: 10},
    { nome: "Ouroeste", codigo: 395, regiao: 7},
    { nome: "Pacaembu", codigo: 396, regiao: 10},
    { nome: "Palestina", codigo: 397, regiao: 7},
    { nome: "Palmares Paulista", codigo: 398, regiao: 7},
    { nome: "Palmeira D´Oeste", codigo: 399, regiao: 7},
    { nome: "Palmital", codigo: 400, regiao: 10},
    { nome: "Panorama", codigo: 401, regiao: 10},
    { nome: "Paraguaçu Paulista", codigo: 402, regiao: 10},
    { nome: "Paraibuna", codigo: 403, regiao: 3},
    { nome: "Paraíso", codigo: 404, regiao: 7},
    { nome: "Paranapanema", codigo: 405, regiao: 9},
    { nome: "Paranapuã", codigo: 406, regiao: 7},   
    { nome: "Parapuã", codigo: 407, regiao: 6},
    { nome: "Pardinho", codigo: 408, regiao: 9},
    { nome: "Pariquera-Açu", codigo: 409, regiao: 8},
    { nome: "Parisi", codigo: 410, regiao: 7},
    { nome: "Patrocínio Paulista", codigo: 411, regiao: 5},
    { nome: "Pauliceia", codigo: 412, regiao: 10},
    { nome: "Paulínia", codigo: 413, regiao: 4},
    { nome: "Paulistânia", codigo: 414, regiao: 6},
    { nome: "Paulo de Faria", codigo: 415, regiao: 7},
    { nome: "Pederneiras", codigo: 416, regiao: 6},
    { nome: "Pedra Bela", codigo: 417, regiao: 4},
    { nome: "Pedranópolis", codigo: 418, regiao: 7},
    { nome: "Pedregulho", codigo: 419, regiao: 5},
    { nome: "Pedreira", codigo: 420, regiao: 4},
    { nome: "Pedrinhas Paulista", codigo: 421, regiao: 10},
    { nome: "Pedro de Toledo", codigo: 422, regiao: 8},
    { nome: "Penápolis", codigo: 423, regiao: 12},
    { nome: "Pereira Barreto", codigo: 424, regiao: 12},
    { nome: "Pereiras", codigo: 425, regiao: 9},
    { nome: "Peruíbe", codigo: 426, regiao: 8},
    { nome: "Piacatu", codigo: 427, regiao: 12},
    { nome: "Piedade", codigo: 428, regiao: 9},
    { nome: "Pilar do Sul", codigo: 429, regiao: 9},
    { nome: "Pindamonhangaba", codigo: 430, regiao: 3},
    { nome: "Pindorama", codigo: 431, regiao: 7},
    { nome: "Pinhalzinho", codigo: 432, regiao: 4},
    { nome: "Piquerobi", codigo: 433, regiao: 10},
    { nome: "Piquete", codigo: 434, regiao: 3},
    { nome: "Piracaia", codigo: 435, regiao: 4},
    { nome: "Piracicaba", codigo: 436, regiao: 11},
    { nome: "Piraju", codigo: 437, regiao: 9},
    { nome: "Pirajuí", codigo: 438, regiao: 6},
    { nome: "Pirangi", codigo: 439, regiao: 5},
    { nome: "Pirapora do Bom Jesus", codigo: 440, regiao: 2},
    { nome: "Pirapozinho", codigo: 441, regiao: 10},
    { nome: "Pirassununga", codigo: 442, regiao: 11},
    { nome: "Piratininga", codigo: 443, regiao: 6},
    { nome: "Pitangueiras", codigo: 444, regiao: 5},
    { nome: "Planalto", codigo: 445, regiao: 7},
    { nome: "Platina", codigo: 446, regiao: 10},
    { nome: "Poá", codigo: 447, regiao: 2},
    { nome: "Poloni", codigo: 448, regiao: 7},
    { nome: "Pompeia", codigo: 449, regiao: 6},
    { nome: "Pongaí", codigo: 450, regiao: 6},
    { nome: "Pontal", codigo: 451, regiao: 5},
    { nome: "Pontalinda", codigo: 452, regiao: 7},
    { nome: "Pontes Gestal", codigo: 453, regiao: 7},
    { nome: "Populina", codigo: 454, regiao: 7},
    { nome: "Porangaba", codigo: 455, regiao: 9},
    { nome: "Porto Feliz", codigo: 456, regiao: 9},
    { nome: "Porto Ferreira", codigo: 457, regiao: 5},
    { nome: "Potim", codigo: 458, regiao: 3},
    { nome: "Potirendaba", codigo: 459, regiao: 7},
    { nome: "Pracinha", codigo: 460, regiao: 10},
    { nome: "Pradópolis", codigo: 461, regiao: 5},
    { nome: "Praia Grande", codigo: 462, regiao: 8},
    { nome: "Pratânia", codigo: 463, regiao: 9},
    { nome: "Presidente Alves", codigo: 464, regiao: 6},
    { nome: "Presidente Bernardes", codigo: 465, regiao: 10},
    { nome: "Presidente Epitácio", codigo: 466, regiao: 10},
    { nome: "Presidente Prudente", codigo: 467, regiao: 10},
    { nome: "Presidente Venceslau", codigo: 468, regiao: 10},
    { nome: "Promissão", codigo: 469, regiao: 6},
    { nome: "Quadra", codigo: 470, regiao: 9},
    { nome: "Quatá", codigo: 471, regiao: 6},
    { nome: "Queiroz", codigo: 472, regiao: 6},
    { nome: "Queluz", codigo: 473, regiao: 3},
    { nome: "Quintana", codigo: 474, regiao: 6},
    { nome: "Rafard", codigo: 475, regiao: 11},
    { nome: "Rancharia", codigo: 476, regiao: 10},
    { nome: "Redenção da Serra", codigo: 477, regiao: 3},
    { nome: "Regente Feijó", codigo: 478, regiao: 10},
    { nome: "Reginópolis", codigo: 479, regiao: 6},
    { nome: "Registro", codigo: 480, regiao: 8},
    { nome: "Restinga", codigo: 481, regiao: 5},
    { nome: "Ribeira", codigo: 482, regiao: 9},
    { nome: "Ribeirão Bonito", codigo: 483, regiao: 5},
    { nome: "Ribeirão Branco", codigo: 484, regiao: 9},
    { nome: "Ribeirão Corrente", codigo: 485, regiao: 5},
    { nome: "Ribeirão do Sul", codigo: 486, regiao: 6},
    { nome: "Ribeirão dos Índios", codigo: 487, regiao: 10},
    { nome: "Ribeirão Grande", codigo: 488, regiao: 9},
    { nome: "Ribeirão Pires", codigo: 489, regiao: 2},
    { nome: "Ribeirão Preto", codigo: 490, regiao: 5},
    { nome: "Rifaina", codigo: 491, regiao: 5},
    { nome: "Rincão", codigo: 492, regiao: 5},
    { nome: "Rinópolis", codigo: 493, regiao: 6},
    { nome: "Rio Claro", codigo: 494, regiao: 11},
    { nome: "Rio das Pedras", codigo: 495, regiao: 11},
    { nome: "Rio Grande da Serra", codigo: 496, regiao: 2},
    { nome: "Riolândia", codigo: 497, regiao: 7},
    { nome: "Riversul", codigo: 498, regiao: 9},
    { nome: "Rosana", codigo: 499, regiao: 10},
    { nome: "Roseira", codigo: 500, regiao: 3},
    { nome: "Rubiácea", codigo: 501, regiao: 12},
    { nome: "Rubineia", codigo: 502, regiao: 7},
    { nome: "Sabino", codigo: 503, regiao: 6},
    { nome: "Sagres", codigo: 504, regiao: 10},
    { nome: "Sales", codigo: 505, regiao: 7},
    { nome: "Sales Oliveira", codigo: 506, regiao: 5},
    { nome: "Salesópolis", codigo: 507, regiao: 2},
    { nome: "Salmourão", codigo: 508, regiao: 10},
    { nome: "Saltinho", codigo: 509, regiao: 11},
    { nome: "Salto", codigo: 510, regiao: 9},
    { nome: "Salto de Pirapora", codigo: 511, regiao: 9},
    { nome: "Salto Grande", codigo: 512, regiao: 6},
    { nome: "Sandovalina", codigo: 513, regiao: 10},
    { nome: "Santa Adélia", codigo: 514, regiao: 7},
    { nome: "Santa Albertina", codigo: 515, regiao: 7},
    { nome: "Santa Bárbara D´Oeste", codigo: 516, regiao: 11},
    { nome: "Santa Branca", codigo: 517, regiao: 3},
    { nome: "Santa Clara D´Oeste", codigo: 518, regiao: 7},
    { nome: "Santa Cruz da Conceição", codigo: 519, regiao: 11},
    { nome: "Santa Cruz da Esperança", codigo: 520, regiao: 5},
    { nome: "Santa Cruz das Palmeiras", codigo: 521, regiao: 11},
    { nome: "Santa Cruz do Rio Pardo", codigo: 522, regiao: 6},
    { nome: "Santa Ernestina", codigo: 523, regiao: 5},
    { nome: "Santa Fé do Sul", codigo: 524, regiao: 7},
    { nome: "Santa Gertrudes", codigo: 525, regiao: 11},
    { nome: "Santa Isabel", codigo: 526, regiao: 2},
    { nome: "Santa Lúcia", codigo: 527, regiao: 5},
    { nome: "Santa Maria da Serra", codigo: 528, regiao: 11},
    { nome: "Santa Mercedes", codigo: 529, regiao: 10},
    { nome: "Santa Rita D´Oeste", codigo: 530, regiao: 7},
    { nome: "Santa Rita do Passa Quatro", codigo: 531, regiao: 5},
    { nome: "Santa Rosa de Viterbo", codigo: 532, regiao: 5},
    { nome: "Santa Salete", codigo: 533, regiao: 7},
    { nome: "Santana da Ponte Pensa", codigo: 534, regiao: 7},
    { nome: "Santana de Parnaíba", codigo: 535, regiao: 2},
    { nome: "Santo Anastácio", codigo: 536, regiao: 10},
    { nome: "Santo André", codigo: 537, regiao: 2},
    { nome: "Santo Antonio da Alegria", codigo: 538, regiao: 5},
    { nome: "Santo Antonio de Posse", codigo: 539, regiao: 4},
    { nome: "Santo Antonio do Aracanguá", codigo: 540, regiao: 12},
    { nome: "Santo Antonio do Jardim", codigo: 541, regiao: 11},
    { nome: "Santo Antonio do Pinhal", codigo: 542, regiao: 3},
    { nome: "Santo Expedito", codigo: 543, regiao: 10},
    { nome: "Santópolis do Aguapeí", codigo: 544, regiao: 12},
    { nome: "Santos", codigo: 545, regiao: 8},
    { nome: "São Bento do Sapucaí", codigo: 546, regiao: 3},
    { nome: "São Bernardo do Campo", codigo: 547, regiao: 2},
    { nome: "São Caetano do Sul", codigo: 548, regiao: 2},
    { nome: "São Carlos", codigo: 549, regiao: 5},
    { nome: "São Francisco", codigo: 550, regiao: 7},
    { nome: "São João da Boa Vista", codigo: 551, regiao: 11},
    { nome: "São João das Duas Pontes", codigo: 552, regiao: 7},
    { nome: "São João de Iracema", codigo: 553, regiao: 12},
    { nome: "São João do Pau D´Alho", codigo: 554, regiao: 10},
    { nome: "São Joaquim da Barra", codigo: 555, regiao: 5},
    { nome: "São José da Bela Vista", codigo: 556, regiao: 5},
    { nome: "São José do Barreiro", codigo: 557, regiao: 3},
    { nome: "São José do Rio Pardo", codigo: 558, regiao: 11},
    { nome: "São José do Rio Preto", codigo: 559, regiao: 7},
    { nome: "São José dos Campos", codigo: 560, regiao: 3},
    { nome: "São Lourenço da Serra", codigo: 561, regiao: 2},
    { nome: "São Luiz do Paraitinga", codigo: 562, regiao: 3},
    { nome: "São Manuel", codigo: 563, regiao: 9},
    { nome: "São Miguel Arcanjo", codigo: 564, regiao: 9},
    { nome: "São Paulo", codigo: 565, regiao: 1},
    { nome: "São Pedro", codigo: 566, regiao: 11},
    { nome: "São Pedro do Turvo", codigo: 567, regiao: 6},
    { nome: "São Roque", codigo: 568, regiao: 9},
    { nome: "São Sebastião", codigo: 569, regiao: 3},
    { nome: "São Sebastião da Grama", codigo: 570, regiao: 11},
    { nome: "São Simão", codigo: 571, regiao: 5},
    { nome: "São Vicente", codigo: 572, regiao: 8},
    { nome: "Sarapuí", codigo: 573, regiao: 9},
    { nome: "Sarutaiá", codigo: 574, regiao: 9},
    { nome: "Sebastianópolis do Sul", codigo: 575, regiao: 7},
    { nome: "Serra Azul", codigo: 576, regiao: 5},
    { nome: "Serra Negra", codigo: 577, regiao: 4},
    { nome: "Serrana", codigo: 578, regiao: 5},
    { nome: "Sertãozinho", codigo: 579, regiao: 5},
    { nome: "Sete Barras", codigo: 580, regiao: 8},
    { nome: "Severínia", codigo: 581, regiao: 5},
    { nome: "Silveiras", codigo: 582, regiao: 3},
    { nome: "Socorro", codigo: 583, regiao: 4},
    { nome: "Sorocaba", codigo: 584, regiao: 9},
    { nome: "Sud Mennucci", codigo: 585, regiao: 12},
    { nome: "Sumaré", codigo: 586, regiao: 11},
    { nome: "Suzanápolis", codigo: 587, regiao: 12},
    { nome: "Suzano", codigo: 588, regiao: 2},
    { nome: "Tabapuã", codigo: 589, regiao: 7},
    { nome: "Tabatinga", codigo: 590, regiao: 5},
    { nome: "Taboão da Serra", codigo: 591, regiao: 2},
    { nome: "Taciba", codigo: 592, regiao: 10},
    { nome: "Taguaí", codigo: 593, regiao: 9},
    { nome: "Taiaçú", codigo: 594, regiao: 5},
    { nome: "Taiuva", codigo: 595, regiao: 5},
    { nome: "Tambaú", codigo: 596, regiao: 11},
    { nome: "Tanabi", codigo: 597, regiao: 7},
    { nome: "Tapiraí", codigo: 598, regiao: 9},
    { nome: "Tapiratiba", codigo: 599, regiao: 11},
    { nome: "Taquaral", codigo: 600, regiao: 5},
    { nome: "Taquaritinga", codigo: 601, regiao: 5},
    { nome: "Taquarituba", codigo: 602, regiao: 9},
    { nome: "Taquarivaí", codigo: 603, regiao: 9},
    { nome: "Tarabaí", codigo: 604, regiao: 10},
    { nome: "Tarumã", codigo: 605, regiao: 10},
    { nome: "Tatuí", codigo: 606, regiao: 9},
    { nome: "Taubaté", codigo: 607, regiao: 3},
    { nome: "Tejupá", codigo: 608, regiao: 9},
    { nome: "Teodoro Sampaio", codigo: 609, regiao: 10},
    { nome: "Terra Roxa", codigo: 610, regiao: 5},
    { nome: "Tietê", codigo: 611, regiao:9},
    { nome: "Timburi", codigo: 612, regiao: 6},
    { nome: "Torre de Pedra", codigo: 613, regiao: 9},
    { nome: "Torrinha", codigo: 614, regiao: 11},
    { nome: "Trabijú", codigo: 615, regiao: 5},
    { nome: "Tremembé", codigo: 616, regiao: 3},
    { nome: "Três Fronteiras", codigo: 617, regiao: 7},
    { nome: "Tuiutí", codigo: 618, regiao: 4},
    { nome: "Tupã", codigo: 619, regiao: 6},
    { nome: "Tupi Paulista", codigo: 620, regiao: 10},
    { nome: "Turiúba", codigo: 621, regiao: 12},
    { nome: "Turmalina", codigo: 622, regiao: 7},
    { nome: "Ubarana", codigo: 623, regiao: 7},
    { nome: "Ubatuba", codigo: 624, regiao: 3},
    { nome: "Ubirajara", codigo: 625, regiao: 6},
    { nome: "Uchôa", codigo: 626, regiao: 7},
    { nome: "União Paulista", codigo: 627, regiao: 7},
    { nome: "Urânia", codigo: 628, regiao: 7},
    { nome: "Uru", codigo: 629, regiao: 6},
    { nome: "Urupês", codigo: 630, regiao: 7},
    { nome: "Valentim Gentil", codigo: 631, regiao: 7},
    { nome: "Valinhos", codigo: 632, regiao: 4},
    { nome: "Valparaíso", codigo: 633, regiao: 12},
    { nome: "Vargem", codigo: 634, regiao: 4},
    { nome: "Vargem Grande do Sul", codigo: 635, regiao: 11},
    { nome: "Vargem Grande Paulista", codigo: 636, regiao: 2},
    { nome: "Várzea Paulista", codigo: 637, regiao: 4},
    { nome: "Vera Cruz", codigo: 638, regiao: 6},
    { nome: "Vinhedo", codigo: 639, regiao: 4},
    { nome: "Viradouro", codigo: 640, regiao: 5},
    { nome: "Vista Alegre do Alto", codigo: 641, regiao: 5},
    { nome: "Vitória Brasil", codigo: 642, regiao: 7},
    { nome: "Votorantim", codigo: 643, regiao: 9},
    { nome: "Votuporanga", codigo: 644, regiao: 7},
    { nome: "Zacarias", codigo: 645, regiao: 7},
]

const removeAccentsAndSpaces = (str) => {
    str = str.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    str = str.replace(/\s+/g, '_');
    return str;
  };
   
  async function webScrapingForCities() {
      const baseDir = 'dadosRegionais';
      const cidadesComErro = [];
   
      try {
          if (!fs.existsSync(baseDir)) {
              fs.mkdirSync(baseDir);
          }
      } catch (err) {
          console.error('Erro ao criar a pasta base:', err);
          return;
      }
   
      const browser = await puppeteer.launch();
   
      for (const cidade of cidadesSP) {
          const nomeArquivo = path.join(baseDir, `${removeAccentsAndSpaces(cidade.nome)}.txt`);
   
          const page = await browser.newPage();
          try {
  await page.goto('https://www.ssp.sp.gov.br/estatistica/dados-mensais');
              await page.waitForSelector('input[type="radio"][name="optradio"]');
              await page.select('input[type="radio"][name="optradio"]', cidade.codigo.toString());
              await page.waitForTimeout(2000);
              await page.setDefaultNavigationTimeout(60000);
  await page.click('#conteudo_btnMensal');
              await page.waitForNavigation();
   
              const tableData = await page.evaluate(() => {
                  const table = document.querySelector('#conteudo_repAnos_gridDados_0 tbody');
                  const rows = table.querySelectorAll('tr');
                  const data = [];
   
                  for (const row of rows) {
                      const columns = row.querySelectorAll('td');
                      const lastColumn = columns[columns.length - 1];
                      const lastCellData = lastColumn ? lastColumn.textContent.trim() : '';
   
                      data.push(lastCellData);
                  }
   
                  return data;
              });
   
              const cidadeData = `${cidade.nome}\n${cidade.codigo}\n${tableData.join('\n')}`;
              fs.writeFileSync(nomeArquivo, cidadeData);
              console.log(`Dados de ${cidade.nome} coletados com sucesso.`);
          } catch (error) {
              console.error(`Erro ao coletar dados de ${cidade.nome}:`, error);
              cidadesComErro.push(cidade.nome);
          } finally {
              await page.close();
          }
      }
   
      await browser.close();
   
      if (cidadesComErro.length > 0) {
          console.log('Cidades com erro na coleta de dados:');
          cidadesComErro.forEach(cidade => {
              console.log(cidade);
          });
      }
  }
   
  webScrapingForCities();



